version: "3"

services:
  reddit:
    image: vitkhab/reddit
    build: .
    ports:
      - 9292:9292
    environment:
      DATABASE_URL: mongodb://mongo:27017
      
  mongo:
    image: mongo:3.6.17
    environment:
      MONGO_INITDB_DATABASE: user_posts
